### ISSUE TITLE
Events should be in a proper namespace

### ISSUE THREAD

**Issue by egahlin** [opentracing-contrib/java-jfr-tracer#26]
The events defined in src/main/java11/io/opentracing/contrib/jfrtracer/impl/jfr/ don't use the @Name annotation, which means JFR will default to the package and the class name ( io.opentracing.contrib.jfrtracer.impl.jfr.JfrSpanEmitterImpl$SpanEvent and
io.opentracing.contrib.jfrtracer.impl.jfr.JfrScopeEmitterImpl$ScopeEvent), which is not suited for programmatic access (and setting files). In particular, "jfr" should be avoided as this is implicit. 

Better names would be "io.opentracing.Span" and "io.opentracing.Scope"

**Comment by thegreystone** [comment]
Very true! Fixed!
