### ISSUE TITLE
Add minimal proxy API for JDK 7 & JDK 8 JFR

### ISSUE THREAD

**Issue by thegreystone** [opentracing-contrib/java-jfr-tracer#4]
We should be able to add a minimal proxy API for the classes and few methods used by the Oracle JDK 7 & 8. This would make it possible to cross compile everything on an Oracle JDK 11 (-release, -source, and -target), and not need an Oracle JDK anymore at compile time.

**Comment by sfriberg** [comment]
Problem will be testing which would require the JDK anyway

**Comment by thegreystone** [comment]
True. Seems TravisCI supports testing with the OracleJDK. :) 

They give as an example: 
.travis.yml
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

Perhaps we can go with oraclejdk8 and openjdk11. 
(Some text indicated that testing oraclejdk7 may no longer work.)
